import random

quotes = [
"A squirrel gathers one acorn and grows stronger over time.",
"Squirrels build success through daily habits.",
"One acorn today supports tomorrow.",
"A focused squirrel never wastes effort.",
"Small acorn piles grow into strong stores.",
"Squirrels prepare early and stay ready.",
"Daily gathering keeps a squirrel secure.",
"A squirrel trusts routine.",
"Each acorn collected proves discipline.",
"Squirrels grow through patience and repetition.",
"A steady squirrel moves with purpose.",
"One branch climbed builds balance.",
"Squirrels train through repetition.",
"A squirrel plans before winter arrives.",
"Strong nests come from steady work.",
"A squirrel values progress over speed.",
"Every acorn adds resilience.",
"Squirrels stay alert and focused.",
"A squirrel learns the forest through experience.",
"Preparation keeps the squirrel confident.",
"A squirrel succeeds through consistency.",
"Each climb strengthens the squirrel.",
"A squirrel stores effort for later.",
"Routine keeps a squirrel sharp.",
"Squirrels grow through daily action.",
"A squirrel never skips gathering.",
"Effort compounds like stored acorns.",
"A squirrel stays disciplined.",
"Strong habits build strong squirrels.",
"Squirrels respect the process.",
"A squirrel works even on quiet days.",
"Every acorn represents commitment.",
"A squirrel moves with intention.",
"Preparation protects the squirrel.",
"Small actions build survival skills.",
"A squirrel trusts steady effort.",
"Progress grows through repetition.",
"A squirrel stays persistent.",
"Daily effort keeps the nest full.",
"A squirrel learns from each climb.",
"Squirrels value preparation.",
"Each acorn strengthens the future.",
"A squirrel keeps momentum.",
"Focus keeps the squirrel efficient.",
"Squirrels build success step by step.",
"A squirrel invests in tomorrow.",
"Stored acorns reflect discipline.",
"A squirrel stays consistent.",
"Strong routines shape strong squirrels.",
"A squirrel avoids shortcuts.",
"Squirrels improve through repetition.",
"Each day adds another acorn.",
"A squirrel stays prepared.",
"Small efforts create security.",
"A squirrel values steady work.",
"Progress follows routine.",
"A squirrel trusts the process.",
"Effort builds endurance.",
"A squirrel stays focused.",
"Consistency fills the nest.",
"A squirrel grows stronger each day.",
"Preparation leads to stability.",
"A squirrel respects patience.",
"Daily action builds confidence.",
"A squirrel stores effort wisely.",
"Strong habits protect progress.",
"A squirrel moves with discipline.",
"Repetition builds mastery.",
"A squirrel prepares for change.",
"Each acorn collected supports growth."
]

shown_recently = []

def get_new_quote():
    available = [q for q in quotes if q not in shown_recently]
    quote = random.choice(available)
    shown_recently.append(quote)
    if len(shown_recently) > 2:
        shown_recently.pop(0)
    return quote 